"\n"
"    -h  --help                  Print this help\n"
"    -v  --version               Print version info\n"
"    -k  --keys                  Print key bindings\n"
"    -n  --aidx  index           Audio stream index    : e.g. 1\n"
"    -o  --adev  device          Audio out device      : e.g. hdmi/local/both/alsa[:device]\n"
"    -i  --info                  Dump stream format and exit\n"
"    -I  --with-info             dump stream format before playback\n"
"    -s  --stats                 Pts and buffer stats\n"
"    -p  --passthrough           Audio passthrough\n"
"    -d  --deinterlace           Force deinterlacing\n"
"        --nodeinterlace         Force no deinterlacing\n"
"        --nativedeinterlace     let display handle interlace\n"
"        --anaglyph type         convert 3d to anaglyph\n"
"        --advanced[=0]          Enable/disable advanced deinterlace for HD videos (default enabled)\n"
"    -w  --hw                    Hw audio decoding\n"
"    -3  --3d mode               Switch tv into 3d mode (e.g. SBS/TB)\n"
"    -M  --allow-mvc             Allow decoding of both views of MVC stereo stream\n"
"    -y  --hdmiclocksync         Display refresh rate to match video (default)\n"
"    -z  --nohdmiclocksync       Do not adjust display refresh rate to match video\n"
"    -t  --sid index             Show subtitle with index\n"
"    -r  --refresh               Adjust framerate/resolution to video\n"
"    -g  --genlog                Generate log file\n"
"    -l  --pos n                 Start position (hh:mm:ss)\n"
"    -b  --blank[=0xAARRGGBB]    Set the video background color to black (or optional ARGB value)\n"
"        --loop                  Loop file. Ignored if file not seekable\n"
"        --no-boost-on-downmix   Don't boost volume when downmixing\n"
"        --vol n                 set initial volume in millibels (default 0)\n"
"        --amp n                 set initial amplification in millibels (default 0)\n"
"        --no-osd                Do not display status information on screen\n"
"        --no-keys               Disable keyboard input (prevents hangs for certain TTYs)\n"
"        --subtitles path        External subtitles in UTF-8 srt format\n"
"        --font path             Default: /usr/share/fonts/truetype/freefont/FreeSans.ttf\n"
"        --italic-font path      Default: /usr/share/fonts/truetype/freefont/FreeSansOblique.ttf\n"
"        --font-size size        Font size in 1/1000 screen height (default: 55)\n"
"        --align left/center     Subtitle alignment (default: left)\n"
"        --no-ghost-box          No semitransparent boxes behind subtitles\n"
"        --lines n               Number of lines in the subtitle buffer (default: 3)\n"
"        --win 'x1 y1 x2 y2'     Set position of video window\n"
"        --win x1,y1,x2,y2       Set position of video window\n"
"        --crop 'x1 y1 x2 y2'    Set crop area for input video\n"
"        --crop x1,y1,x2,y2      Set crop area for input video\n"
"        --aspect-mode type      Letterbox, fill, stretch. Default: stretch if win is specified, letterbox otherwise\n"
"        --audio_fifo  n         Size of audio output fifo in seconds\n"
"        --video_fifo  n         Size of video output fifo in MB\n"
"        --audio_queue n         Size of audio input queue in MB\n"
"        --video_queue n         Size of video input queue in MB\n"
"        --threshold   n         Amount of buffered data required to finish buffering [s]\n"
"        --timeout     n         Timeout for stalled file/network operations (default 10s)\n"
"        --orientation n         Set orientation of video (0, 90, 180 or 270)\n"
"        --fps n                 Set fps of video where timestamps are not present\n"
"        --live                  Set for live tv or vod type stream\n"
"        --layout                Set output speaker layout (e.g. 5.1)\n"
"        --dbus_name name        default: org.mpris.MediaPlayer2.omxplayer\n"
"        --key-config <file>     Uses key bindings in <file> instead of the default\n"
"        --alpha                 Set video transparency (0..255)\n"
"        --layer n               Set video render layer number (higher numbers are on top)\n"
"        --display n             Set display to output to\n"
"        --cookie 'cookie'       Send specified cookie as part of HTTP requests\n"
"        --user-agent 'ua'       Send specified User-Agent as part of HTTP requests\n"
"        --lavfdopts 'opts'      Options passed to libavformat, e.g. 'probesize:250000,...'\n"
"        --avdict 'opts'         Options passed to demuxer, e.g., 'rtsp_transport:tcp,...'\n"
"        --sync-server                    Designate this node as the server\n"
"        --server-port <server_port>      Synchronization server tcp port\n"
"        --sync-client                    Designate this node as a client\n"
"        --server-address <server_ip>     Synchronization server name or ip address\n"
"        --sync-num-clients <num_clients> Exact number of clients being synchronized\n"
"                                         Where num clients = num nodes - 1\n"
"        --verbose-sync                   Output Synchronization data\n"
"\n"
"For example:\n"
"\n"
"    ./omxplayer -p -o hdmi test.mkv\n"
"\n"
