"\n"
"Key bindings to control omxplayer while playing:\n"
"\n"
"    1           decrease speed\n"
"    2           increase speed\n"
"    <           rewind\n"
"    >           fast forward\n"
"    z           show info\n"
"    j           previous audio stream\n"
"    k           next audio stream\n"
"    i           previous chapter\n"
"    o           next chapter\n"
"    n           previous subtitle stream\n"
"    m           next subtitle stream\n"
"    s           toggle subtitles\n"
"    w           show subtitles\n"
"    x           hide subtitles\n"
"    d           decrease subtitle delay (- 250 ms)\n"
"    f           increase subtitle delay (+ 250 ms)\n"
"    q           exit omxplayer\n"
"    p / space   pause/resume\n"
"    -           decrease volume\n"
"    + / =       increase volume\n"
"    left arrow  seek -30 seconds\n"
"    right arrow seek +30 seconds\n"
"    down arrow  seek -600 seconds\n"
"    up arrow    seek +600 seconds\n"
"\n"
